import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";
import { OpenAIKeyProvider } from "@/provider/OpenAIKeyProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "LiveWithCodeAnkit",
  description: "Generated by LiveWithCodeAnkit",
  openGraph: {
    title: "LiveWithCodeAnkit",
    description: "Generated by LiveWithCodeAnkit",
    url: "https://github.com/LiveWithCodeAnkit",
    siteName: "LiveWithCodeAnkit",
    locale: "en_US",
    type: "website",
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <OpenAIKeyProvider>
            <Header />
            {children}
          </OpenAIKeyProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
